---
- name: Update Windows Security Package using URL
  hosts: all
  roles:
    - role: upgrade_win_package
      security_update_url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/secu/2024/03/windows10.0-kb5036604-x64_b83a6ea8550712befd70d19518d8d519426631a0.msu"
  tags: [url]
