---
- name: Ping Windows Machine
  win_ping:
  tags: [detect_os, splunk_version]

- name: Gather OS specific variables
  ansible.builtin.setup:
    gather_subset:
      - "all"
  tags: [detect_os, splunk_version]

- name: Print all available facts for debugging
  ansible.builtin.debug:
    var: ansible_facts
  ignore_errors: yes 
  tags: [detect_os, splunk_version]

- name: Set OS family fact
  ansible.builtin.set_fact:
    os_family: "{{ ansible_os_family }}"
  tags: [detect_os, splunk_version]

- name: Set OS major version fact
  ansible.builtin.set_fact:
    os_version_major: "{{ ansible_distribution_major_version | default('undefined') }}"
  when: ansible_distribution_major_version is defined
  tags: [detect_os, splunk_version]

- name: Set OS minor version fact
  ansible.builtin.set_fact:
    os_version_minor: "{{ ansible_distribution_minor_version | default('undefined') }}"
  when: ansible_distribution_minor_version is defined
  tags: [detect_os, splunk_version]

