---
# tasks file for splunk_forwarder_pkg_update
- include_tasks: detect_os.yml
  tags: [splunk_version]

- name: Validate inventories facts
  ansible.builtin.include_tasks: check_splunk_version.yml
  tags: [splunk_version]

- name: Ensure the appropriate state of Splunk Forwarder
  tags: [splunk_execute]
  block:
    - include_tasks: install_splunk.yml
      when: splunk_forwarder_state == "present" and splunk_version_mismatch is defined and splunk_version_mismatch == false

    - include_tasks: update_splunk.yml
      when: splunk_forwarder_state == "present" and splunk_version_mismatch is defined and splunk_version_mismatch == true

    - include_tasks: remove_splunk.yml
      when: splunk_forwarder_state == "absent"
